services:
  - type: web
    name: pulseops-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulseops-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: pulseops-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: keyvalue
    name: pulseops-redis
    plan: free
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: pulseops-postgres
    plan: free
    region: oregon
    databaseName: pulseops
    user: pulseops
    ipAllowList: []
