apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulseops.fullname" . }}-secrets
  labels:
    {{- include "pulseops.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
